apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: token-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: active.token-test.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: token-test-active-service
              servicePort: 5000
    - host: preview.token-test.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: token-test-preview-service
              servicePort: 5000
